version: '3.2'
services:
  integration_test:
    build:
      context: .
    restart: always
    environment:
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
      - MANAGE_INDICES=true
      - WAIT_TIMEOUT=30000
      - LOG_LEVEL=info
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_SESSION_TOKEN=local
    depends_on:
      - elasticsearch
    entrypoint: "./scripts/wait-es-and-test.sh"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "action.auto_create_index=true"
    ports:
      - "9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
